#include "framework.h"
#include "guitar.h"
#include "resource.h"
#include <Xinput.h>

BUTTON_INFO buttons[BUTTON_COUNT] = {
	[GREEN] = { XINPUT_GAMEPAD_A, IDC_GREEN, NULL },
	[RED] = { XINPUT_GAMEPAD_B, IDC_RED, NULL },
	[YEELOW] = { XINPUT_GAMEPAD_Y, IDC_YEELOW, NULL },
	[BLUE] = { XINPUT_GAMEPAD_X, IDC_BLUE, NULL },
	[ORANGE] = { XINPUT_GAMEPAD_LEFT_SHOULDER, IDC_ORANGE, NULL },

	[UP_STRUM] = { XINPUT_GAMEPAD_DPAD_UP, IDC_UP, NULL },
	[DOWN_STRUM] = { XINPUT_GAMEPAD_DPAD_DOWN, IDC_DOWN, NULL },
	[LEFT] = { XINPUT_GAMEPAD_DPAD_LEFT, IDC_LEFT, NULL },
	[RIGHT] = { XINPUT_GAMEPAD_DPAD_RIGHT, IDC_RIGHT, NULL },

	[START] = { XINPUT_GAMEPAD_START, IDC_START, NULL },
	[SELECT] = { XINPUT_GAMEPAD_BACK, IDC_SELECT, NULL }
};
